version: "3.8"
services:
    nginx:
        build: ./nginx
        container_name: nginx
        networks:
            - thenet
        ports:
            - '8080:8080'
    app:
        build: ./app
        container_name: app
        networks:
            - thenet
        ports:
            - '3000:3000'

networks:
    thenet: